# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aPbSoJt7C0D7UogxuOucDOKTH7C-YMd

Import Libraries & Load Data
"""

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# ML tools
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Models
from sklearn.ensemble import RandomForestClassifier

# Load dataset (upload in Colab or use path)
df = pd.read_csv('/content/nanotox_dataset.csv')

df.head()

"""Data Preprocessing

🔹 Handle Missing Values
"""

df.isnull().sum()

# Simple approach
df.fillna(df.mean(numeric_only=True), inplace=True)

"""🔹 Encode Categorical Column (NPs)"""

le_np = LabelEncoder()
df['NPs'] = le_np.fit_transform(df['NPs'])

"""🔹 Encode Target Variable"""

le_target = LabelEncoder()
df['class'] = le_target.fit_transform(df['class'])  # toxic = 1, nonToxic = 0

"""🔹 Feature Scaling"""

X = df.drop('class', axis=1)
y = df['class']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

"""Model Training (Baseline)"""

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""Avoid Overfitting (Hyperparameter Tuning)"""

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5, 10]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy'
)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_

y_pred = best_model.predict(X_test)

print("Best Parameters:", grid.best_params_)
print("Accuracy:", accuracy_score(y_test, y_pred))

"""Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""Feature Importance"""

importances = best_model.feature_importances_

feature_names = X.columns

feat_imp = pd.Series(importances, index=feature_names)
feat_imp.sort_values().plot(kind='barh')

plt.title("Feature Importance")
plt.show()